services:
  server:
    container_name: zabo-server
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports: 
      - 6001:6001 
    volumes:
      - .:/app
  mongo:
    image: mongo 
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongo-volume:/data/db
  redis:
    image: redis 
    restart: always
    volumes:
      - redis-volume:/data
    ports:
      - 6379:6379

volumes:
  mongo-volume:
    external: false 
  redis-volume:
    external: false 
