apiVersion: v1
kind: ConfigMap
metadata:
  name: zabo-env
data:
  NODE_ENV: "production"
  SSO_CLIENT_ID: "00"
  AWS_ACCESS_KEY_ID: "00"
  S3_BUCKET: "sparcs-kaist-zabo-prod"
  MONGODB_URL: "mongodb://mongodb-tset-mongodb-sharded/zabo"
  REDIS_URL: "zabo-redis-service"
